### ISSUE TITLE
Node positions no longer being saved

### ISSUE THREAD

**Issue by Slow-Dog** [dmungin/gloomhaven-scenario-tree-ng#13]
It used to be possible to drag nodes around, and the position of those nodes was saved in the data. I've previously moved all the nodes to an ordering which matched my group's campaign progress. Suddenly none of nodes are where I put them, and the position doesn't appear to stick. I can't see the position information in the data any more. Has this feature been removed?

**Comment by dmungin** [comment]
Yes as part of simplifying the saved JSON I removed the positioning. I hadn't actually considered that anyone would be using that saved information to move scenarios around like you said. Hopefully it didn't mess you up too much. I'll work on a fix tomorrow.
