### ISSUE TITLE
Scenario 31 (Plane of Night) should be locked if 14 (Frozen Hollow) is incomplete

### ISSUE THREAD

**Issue by Xelecium** [dmungin/gloomhaven-scenario-tree-ng#17]
I have Scenario 31 unlocked by way of 1->2->4->5->10->22->31, but it is not currently greyed out.
Scenario 14 completion is a requirement (via Global Achievement) for 31 to be playable.

**Comment by dmungin** [comment]
should be fixed now. Thanks.
