### ISSUE TITLE
Import/export text is incorrect on scenarios with 2 or more treasures

### ISSUE THREAD

**Issue by mccracken02** [dmungin/gloomhaven-scenario-tree-ng#19]
On a scenario where there are two or more treasure tiles, for example scenario 4, the import/export data does not seem to generate correctly.

To be specific, if you loot both treasures, then examine the import/export tool, the generated output will only show one of the treasures. I have tried the reverse, manually editing the import data to include the missing treasure, and the import seems to process correctly. So it seems the problem lies only in generating the export text.

**Comment by dmungin** [comment]
Should be resolved now
