### ISSUE TITLE
Node IDs not matching up with import/export strings after today's update

### ISSUE THREAD

**Issue by dasurge0** [dmungin/gloomhaven-scenario-tree-ng#22]
As of a couple of days ago, my scenario tree for my party was accurate. Today it lists incorrect scenarios (placement of dots seems correct though scenarios associated with dots is wrong).

For example, the node for Scenario 83 was replaced with the node for Scenario 81, including notes definitely added for Scenario 83. Please see the attached import string as an example. 
The string contains a Notes attribute for Scenario 83 but when imported and rendered, you'll see the note for Scenario 81 and not 83.

Thanks! This is an awesome project!

**Comment by dmungin** [comment]
Can you check now? It should be fixed.

**Comment by dasurge0** [comment]
Thanks, I can confirm that this is resolved now. Much appreciated!
