### ISSUE TITLE
Node color not updating properly after unlock

### ISSUE THREAD

**Issue by tehske** [dmungin/gloomhaven-scenario-tree-ng#25]
When marking a scenario as completed, sometimes unlocked scenarios aren't marked as grey for locked properly.

To reproduce, reset and unlock in this order: 1, 2, 3, 9, 11, 18. Now 26 will be black, but if you select any node (except 26), it will update to grey for locked.

**Comment by dmungin** [comment]
Thanks, I'm looking into it.

**Comment by dmungin** [comment]
This should be fixed now
