### ISSUE TITLE
Treasure Chest Reward Wrong - Scenario 49 / Chest 44

### ISSUE THREAD

**Issue by Porkchopp** [dmungin/gloomhaven-scenario-tree-ng#26]
Hi,

I noticed after we opened the Chest 44 in Scenario 49 that it says 'Random Item Design', while in the scenario book it is actually 'Random Side Scenario'.  Just wanted to let you know!

Thanks!

**Comment by technokelvin** [comment]
Thank you for pointing this out!

**Comment by dmungin** [comment]
Thanks for the fix, merged and built.

**Comment by technokelvin** [comment]
Thank you for the great application! I hope to contribute more in the near future. :-)
