### ISSUE TITLE
Scenario Tree doesn't seem to contain scenario 87?

### ISSUE THREAD

**Issue by ScotAnderson** [dmungin/gloomhaven-scenario-tree-ng#3]
My ground unlocked scenario 87 via a city event, so if it is normally part of a tree we skipped any scenarios that lead up to it.

**Comment by shawndibble** [comment]
scenario 87 requires you to complete 86 to do. So it seems maybe requirement line from 86 to 87 is needed.

**Comment by dmungin** [comment]
This case is a bit strange as a city event unlocks 87 as you said but you still need to unlock 86 and complete it according to the required party achievements listed on 87. I'll try to merge your pull request to resolve it.
