### ISSUE TITLE
Completing #36 doesn't lock #21

### ISSUE THREAD

**Issue by ScotAnderson** [dmungin/gloomhaven-scenario-tree-ng#4]
My group just completed scenario #36, which gives the global achievement TRN. This achievement being incomplete is a requirement for #21, so I expected it to turn red and be unavailable. It doesn't.

**Comment by shawndibble** [comment]
Seems this has been fixed with the latest version of the code. Unfortunately, that may require you to update the import file if you don't have it already. This is the pertinent info you need.

```
        {
            "data": {
                "source": "36",
                "target": "21",
                "type": "blocks"
            }
        },
```

**Comment by dmungin** [comment]
I've updated the way the JSON is saved so only scenario status and notes are saved. This issue was resolved in a previous fix and now manually updating of local JSON should not be necessary after exporting the new format.
