### ISSUE TITLE
Scenario 43 - Drake Nest, should unlock Scenario 26 - Ancient Cistern

### ISSUE THREAD

**Issue by jacktokarz** [dmungin/gloomhaven-scenario-tree-ng#49]
It also unlocks 37, but I already had that one, so I can't be sure if it would have or not.

**Comment by leejjones** [comment]
Actually, 43 does NOT unlock 26 or 37. Notice that these are mentioned in the conclusion, but are not listed as "New Locations." The mention of 26 and 37 are just hints that you should go back to those locations if they are available to you.

**Comment by jacktokarz** [comment]
Oh good catch, I didn't pick up on that distinction. I just got used to seeing the circled number and assuming that meant an unlock. Thanks for sharing this great project!
